### ISSUE TITLE
looks like a deploy error, holding off on the starting the socket

### ISSUE THREAD

**Issue by kamraanki** [IBM-Blockchain/cp-web#29]
I have created local dev network (2 vp and CA, running with pbft batch consensus). I deployed cp-web, user registration was successful, but it gives following error:-

 { name: 'deploy() error',
  code: 500,
  details:
   { [Error: write EPROTO 140556406359936:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:782:
   ] code: 'EPROTO', errno: 'EPROTO', syscall: 'write' } }

I have disabled TLS in options of mycreds.json

**Comment by himanshutyagi36** [comment]
@kamraanki I'm facing the same issue. Did you solve it ?

**Comment by kamraanki** [comment]
@tortuga90 No i am still facing the same issue.

**Comment by krishvoor** [comment]
@kamraanki & @tortuga90 Count me in, I am facing the same issue right now, did you guys have any chance solving it.

**Comment by dshuffma-ibm** [comment]
this line concerns me:

```
I have disabled TLS in options of mycreds.json
```

The correct way to disable TLS is in the options object in app.js, near network options. Here is a [section](https://github.com/IBM-Blockchain/marbles/blob/master/tutorial_part1.md#configure-the-sdk-for-your-blockchain-network) written for marbles that should help.

In summary you need to **add** an `option` field to [app.js](https://github.com/IBM-Blockchain/cp-web/blob/master/app.js#L214) so that it looks like:

``` js
network:{
        peers: [peers[0]],
        users: users,   
        options: {
                tls: false
        }
...
```

just for more clarification this `tls:false` field is telling the [REST based SDK](https://github.com/IBM-Blockchain/ibm-blockchain-js) to use http vs https.

**Comment by himanshutyagi36** [comment]
@dshuffma-ibm I've disabled in the app.js itself.

**Comment by dshuffma-ibm** [comment]
could you post more logs?  does it register any enrollIDs with a peer successfully? also @tortuga90 are you  also using your own **local network**?

**Comment by himanshutyagi36** [comment]
@dshuffma-ibm yes, I'm running on my local network. The CA and Validating peer are in Vagrant VM, and the node.js app is running from outside the vagrant vm

**Comment by dshuffma-ibm** [comment]
cp-web is not updated to work with the new hyperledger fabric.  We have people working to update it, but it is not yet ready. You should hold off on using cp-web until we push an updated version. [Marbles](https://github.com/IBM-Blockchain/marbles) however will work fine.

**Comment by tmh1999** [comment]
@dshuffma-ibm  Please let me use this thread to ask a related question to marble. I am using marble and having this problem when running **$ gulp**  at marbles/ root directory:

```
     Waiting...
[ibc-js] deploy - failure: 500
! looks like a deploy error, holding off on the starting the socket
 { name: 'deploy() error',
  code: 500,
  details: 
   { Error: Parse Error
       at Error (native)
       at Socket.socketOnData (_http_client.js:361:20)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:172:18)
       at Socket.Readable.push (_stream_readable.js:130:10)
       at TCP.onread (net.js:542:20) bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' } }
```

My local dev is 2vp & CA using docker-compose.yml like this :

```
membersrvc:
  image: hyperledger/fabric-membersrvc
  command: membersrvc
vp0:
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=http://172.17.0.1:2375
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_ID=vp0
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=111111111111
  command: peer node start
vp1:
  extends:
    service: vp0
  environment:
    - CORE_PEER_ID=vp1
    - CORE_SECURITY_ENROLLID=test_vp1
    - CORE_SECURITY_ENROLLSECRET=111111111111
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:30303
  links:
    - vp0
```

And my marbles/mycreds.json :

```
{
  "credentials": {
    "peers": [
      {
        "api_host": "172.17.0.2",
        "api_port_tls": 30303,
        "api_port": 30303,
        "id": "vp0"
      }
    ],
    "users": [
      {
        "enrollId": "test_vp0",
        "enrollSecret": "111111111111"
      }
    ]
  }
}
```

I have disabled tls in marbles/app.js.
